dist: trusty
sudo: required
language: ruby
cache:
  bundler: true
rvm:
  - 2.4.1-clang
addons:
  postgresql: '9.6'
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c "CREATE DATABASE open_lis_test ENCODING 'UTF-8';" -U postgres
