dist: trusty
sudo: required
language: ruby
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - gem update --system
cache:
  bundler: true
  yarn: true
rvm:
  - 2.5.1-clang
addons:
  postgresql: '10'
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c "CREATE DATABASE open_lis_test ENCODING 'UTF-8';" -U postgres
