dist: trusty
sudo: required
language: ruby
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  bundler: true
  yarn: true
rvm:
  - 2.4.2-clang
addons:
  postgresql: '9.6'
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c "CREATE DATABASE open_lis_test ENCODING 'UTF-8';" -U postgres
