default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: open_lis_development

test:
  <<: *default
  database: open_lis_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: open_lis_production
    username: open_lis
    password: <%= ENV["POSTGRES_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: open_lis_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: open_lis_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: open_lis_production_cable
    migrations_paths: db/cable_migrate
