default: &default
  adapter: postgresql
  encoding: utf-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: open_lis_development

test:
  <<: *default
  database: open_lis_test

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: open_lis_production
  username: open_lis
  password: <%= ENV["POSTGRES_PASSWORD"] %>
