class BigintIds < ActiveRecord::Migration[5.1]
  def up
    change_column :accession_panels, :id, :bigint
    change_column :accession_panels, :accession_id, :bigint
    change_column :accession_panels, :panel_id, :bigint
    change_column :accessions, :id, :bigint
    change_column :accessions, :patient_id, :bigint
    change_column :accessions, :drawer_id, :bigint
    change_column :accessions, :receiver_id, :bigint
    change_column :accessions, :reporter_id, :bigint
    change_column :accessions, :doctor_id, :bigint
    change_column :claims, :id, :bigint
    change_column :claims, :accession_id, :bigint
    change_column :claims, :insurance_provider_id, :bigint
    change_column :departments, :id, :bigint
    change_column :doctors, :id, :bigint
    change_column :insurance_providers, :id, :bigint
    change_column :insurance_providers, :price_list_id, :bigint
    change_column :lab_test_panels, :id, :bigint
    change_column :lab_test_panels, :lab_test_id, :bigint
    change_column :lab_test_panels, :panel_id, :bigint
    change_column :lab_test_value_option_joints, :id, :bigint
    change_column :lab_test_value_option_joints, :lab_test_value_id, :bigint
    change_column :lab_test_value_option_joints, :lab_test_id, :bigint
    change_column :lab_test_values, :id, :bigint
    change_column :lab_tests, :id, :bigint
    change_column :lab_tests, :department_id, :bigint
    change_column :lab_tests, :unit_id, :bigint
    change_column :notes, :id, :bigint
    change_column :notes, :department_id, :bigint
    change_column :notes, :noticeable_id, :bigint
    change_column :panels, :id, :bigint
    change_column :patients, :id, :bigint
    change_column :patients, :insurance_provider_id, :bigint
    change_column :price_lists, :id, :bigint
    change_column :prices, :id, :bigint
    change_column :prices, :price_list_id, :bigint
    change_column :prices, :priceable_id, :bigint
    change_column :reference_ranges, :id, :bigint
    change_column :reference_ranges, :lab_test_id, :bigint
    change_column :results, :id, :bigint
    change_column :results, :lab_test_id, :bigint
    change_column :results, :accession_id, :bigint
    change_column :results, :lab_test_value_id, :bigint
    change_column :units, :id, :bigint
    change_column :users, :id, :bigint
  end

  def down
    change_column :accession_panels, :id, :integer
    change_column :accession_panels, :accession_id, :integer
    change_column :accession_panels, :panel_id, :integer
    change_column :accessions, :id, :integer
    change_column :accessions, :patient_id, :integer
    change_column :accessions, :drawer_id, :integer
    change_column :accessions, :receiver_id, :integer
    change_column :accessions, :reporter_id, :integer
    change_column :accessions, :doctor_id, :integer
    change_column :claims, :id, :integer
    change_column :claims, :accession_id, :integer
    change_column :claims, :insurance_provider_id, :integer
    change_column :departments, :id, :integer
    change_column :doctors, :id, :integer
    change_column :insurance_providers, :id, :integer
    change_column :insurance_providers, :price_list_id, :integer
    change_column :lab_test_panels, :id, :integer
    change_column :lab_test_panels, :lab_test_id, :integer
    change_column :lab_test_panels, :panel_id, :integer
    change_column :lab_test_value_option_joints, :id, :integer
    change_column :lab_test_value_option_joints, :lab_test_value_id, :integer
    change_column :lab_test_value_option_joints, :lab_test_id, :integer
    change_column :lab_test_values, :id, :integer
    change_column :lab_tests, :id, :integer
    change_column :lab_tests, :department_id, :integer
    change_column :lab_tests, :unit_id, :integer
    change_column :notes, :id, :integer
    change_column :notes, :department_id, :integer
    change_column :notes, :noticeable_id, :integer
    change_column :panels, :id, :integer
    change_column :patients, :id, :integer
    change_column :patients, :insurance_provider_id, :integer
    change_column :price_lists, :id, :integer
    change_column :prices, :id, :integer
    change_column :prices, :price_list_id, :integer
    change_column :prices, :priceable_id, :integer
    change_column :reference_ranges, :id, :integer
    change_column :reference_ranges, :lab_test_id, :integer
    change_column :results, :id, :integer
    change_column :results, :lab_test_id, :integer
    change_column :results, :accession_id, :integer
    change_column :results, :lab_test_value_id, :integer
    change_column :units, :id, :integer
    change_column :users, :id, :integer
  end
end
