name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - development
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: runner
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Bundle install
        env:
          RAILS_ENV: test
        run: |
          gem update --system > /dev/null
          gem update bundler > /dev/null
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Webpacker compile
        env:
          RAILS_ENV: test
        run: |
          npm install yarn
          yarn install
          bundle exec rails webpacker:install
          bundle exec rake assets:precompile
          bundle exec rails webpacker:compile

      - name: Setup database
        env:
          RAILS_ENV: test
        run: bin/rails db:reset db:test:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bin/rails test
          bin/rails test:system
