name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - development
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: runner
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false

      - name: XXX debug
        run: bundle update debug

      - name: Setup database
        env:
          RAILS_ENV: test
        run: bin/rails db:reset db:test:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails test:all

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: capybara
          path: ./tmp/capybara/
