name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - development
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: runner
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Webpacker compile
        env:
          RAILS_ENV: test
        run: |
          npm install yarn
          yarn install
          bundle exec rails webpacker:install
          bundle exec rake assets:precompile
          bundle exec rails webpacker:compile

      - name: Setup database
        env:
          RAILS_ENV: test
        run: bin/rails db:reset db:test:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails test:all
